import "./globals.css";
import Header from "@/Components/Header";

export const metadata = {
  title: "myquizapp",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning>
        <Header />
        {children}
      </body>
    </html>
  );
}
